#!/bin/sh

#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=24gb:ngpus=1:gpu_type=RTX6000

cd /rds/general/user/kll119/home/fargo3d_photoevap
module load intel-suite/2020.2 cuda/10.1

export CUDA=$CUDA_HOME
nvidia-smi

nvidia_smi_output=$(nvidia-smi)

if [[ "$nvidia_smi_output" == *"P1000"* ]]
then
    echo "Running on P1000. Cancelling job."
    exit 0
fi

./run_photoevap.sh {{SETUPNAME}}

module unload intel-suite/2020.2 cuda/10.1